
[

    Info = 
        [
            
            Name = "Portal",
            DocumentType = "Library"

        ],






    Content = 
        {


            [   // LibaryEntry1
            
                Name = "Portal.LibaryEntry1",
                Type = "Function",
                Content = 
                    (
            
            
                        let h = 500 in h
            
            
                    )
            ]


        }







]
